services:
  xttsapiserver:
    image: xttsapiserver
    env_file: .env
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - "${HOST_PORT:-8020}:${CONTAINER_PORT:-8020}"
    volumes:
      - ./xtts-server:/xtts-server
      - ../example:/xtts-server/speakers/example:ro
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]